# <font color=green> PYTHON PARA DATA SCIENCE - NUMPY
---

# <font color=green> 1. INTRODUÇÃO AO PYTHON
---

# 1.1 Introdução

> Python é uma linguagem de programação de alto nível com suporte a múltiplos paradigmas de programação. É um projeto *open source* e desde seu surgimento, em 1991, vem se tornando uma das linguagens de programação interpretadas mais populares. 
>
> Nos últimos anos Python desenvolveu uma comunidade ativa de processamento científico e análise de dados e vem se destacando como uma das linguagens mais relevantes quando o assunto é ciência de dados e machine learning, tanto no ambiente acadêmico como também no mercado.

# 1.2 Instalação e ambiente de desenvolvimento

### Instalação Local

### https://www.python.org/downloads/
### ou
### https://www.anaconda.com/distribution/

### Google Colaboratory

### https://colab.research.google.com

### Verificando versão

In [3]:
!python -V

Python 3.8.11


# 1.3 Trabalhando com arrays Numpy

#### Quando colocamos exclamação("!") é possível rodar o comandos bash como se fosse no terminal de sistema operacional que está utilizando.

In [4]:
#!pip3 install numpy

In [5]:
import numpy as np

In [6]:
km = np.loadtxt('./data/carros-km.txt')
km

array([4.44100e+04, 5.71200e+03, 3.71230e+04, 0.00000e+00, 2.57570e+04,
       1.07280e+04, 0.00000e+00, 7.75990e+04, 9.91970e+04, 3.79780e+04,
       1.28590e+04, 8.05200e+03, 8.97730e+04, 0.00000e+00, 4.14570e+04,
       1.15607e+05, 4.64490e+04, 0.00000e+00, 3.70860e+04, 1.51730e+04,
       1.01193e+05, 0.00000e+00, 9.80790e+04, 1.02959e+05, 0.00000e+00,
       0.00000e+00, 5.79500e+03, 0.00000e+00, 5.88480e+04, 9.43810e+04,
       3.01630e+04, 5.33320e+04, 1.77200e+04, 3.38080e+04, 9.06840e+04,
       4.39750e+04, 0.00000e+00, 0.00000e+00, 5.52600e+03, 0.00000e+00,
       9.34150e+04, 4.07620e+04, 0.00000e+00, 8.63020e+04, 0.00000e+00,
       9.75500e+03, 6.99450e+04, 2.39500e+03, 0.00000e+00, 8.03490e+04,
       8.55540e+04, 5.04960e+04, 6.77160e+04, 9.39470e+04, 3.53450e+04,
       8.10070e+04, 1.19513e+05, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 1.18895e+05, 4.85090e+04, 1.00912e+05,
       9.56490e+04, 0.00000e+00, 9.04950e+04, 0.00000e+00, 2.913

In [7]:
anos = np.loadtxt('data/carros-anos.txt', dtype=int)
anos

array([2003, 1991, 1990, 2019, 2006, 2012, 2019, 2009, 2010, 2011, 2002,
       2007, 2001, 2019, 2009, 2016, 2012, 2019, 2016, 2017, 2002, 2019,
       1994, 1991, 2019, 2019, 2016, 2019, 2002, 1991, 1997, 1995, 2018,
       1991, 2014, 1995, 2019, 2019, 2009, 2019, 2013, 2003, 2019, 2002,
       2019, 2002, 2004, 2001, 2019, 2003, 2009, 2006, 2000, 2006, 2010,
       1994, 2007, 2019, 2019, 2019, 2019, 2019, 2017, 2011, 2001, 1996,
       2019, 1994, 2019, 2007, 1994, 2007, 1997, 2006, 2013, 1994, 2008,
       2008, 2019, 2019, 1999, 2007, 1993, 1995, 2019, 2019, 2016, 2011,
       2019, 2002, 2013, 2017, 2016, 2008, 2018, 2003, 2003, 2004, 2010,
       2019, 2006, 2001, 2019, 2015, 2018, 2017, 1992, 2001, 1993, 1995,
       2003, 2014, 2008, 2013, 2019, 2017, 2019, 2019, 2006, 2015, 2007,
       2005, 2017, 1998, 2019, 1999, 2019, 2009, 2003, 1994, 2019, 1994,
       2019, 2015, 1996, 1997, 1993, 2019, 1992, 1995, 2019, 1990, 2019,
       2019, 1991, 1990, 2012, 2007, 2013, 2000, 20

### Defining two function to handle with print data from "km" and "anos":

In [8]:
def imprime_km(km):
    return print(f'Numpy array de km({km.dtype} e o Tipo de Objeto é {type(km)}): \n\n {km} \n')

def imprime_anos(anos):
    return print(f'Numpy array de anos({anos.dtype} e o Tipo de Objeto é {type(anos)}): \n\n {anos}')

In [9]:
imprime_km(km)

Numpy array de km(float64 e o Tipo de Objeto é <class 'numpy.ndarray'>): 

 [4.44100e+04 5.71200e+03 3.71230e+04 0.00000e+00 2.57570e+04 1.07280e+04
 0.00000e+00 7.75990e+04 9.91970e+04 3.79780e+04 1.28590e+04 8.05200e+03
 8.97730e+04 0.00000e+00 4.14570e+04 1.15607e+05 4.64490e+04 0.00000e+00
 3.70860e+04 1.51730e+04 1.01193e+05 0.00000e+00 9.80790e+04 1.02959e+05
 0.00000e+00 0.00000e+00 5.79500e+03 0.00000e+00 5.88480e+04 9.43810e+04
 3.01630e+04 5.33320e+04 1.77200e+04 3.38080e+04 9.06840e+04 4.39750e+04
 0.00000e+00 0.00000e+00 5.52600e+03 0.00000e+00 9.34150e+04 4.07620e+04
 0.00000e+00 8.63020e+04 0.00000e+00 9.75500e+03 6.99450e+04 2.39500e+03
 0.00000e+00 8.03490e+04 8.55540e+04 5.04960e+04 6.77160e+04 9.39470e+04
 3.53450e+04 8.10070e+04 1.19513e+05 0.00000e+00 0.00000e+00 0.00000e+00
 0.00000e+00 0.00000e+00 1.18895e+05 4.85090e+04 1.00912e+05 9.56490e+04
 0.00000e+00 9.04950e+04 0.00000e+00 2.91320e+04 2.38020e+04 8.49920e+04
 5.43950e+04 2.67310e+04 4.43290e+04 1.18236e+05

In [10]:
imprime_anos(anos)

Numpy array de anos(int32 e o Tipo de Objeto é <class 'numpy.ndarray'>): 

 [2003 1991 1990 2019 2006 2012 2019 2009 2010 2011 2002 2007 2001 2019
 2009 2016 2012 2019 2016 2017 2002 2019 1994 1991 2019 2019 2016 2019
 2002 1991 1997 1995 2018 1991 2014 1995 2019 2019 2009 2019 2013 2003
 2019 2002 2019 2002 2004 2001 2019 2003 2009 2006 2000 2006 2010 1994
 2007 2019 2019 2019 2019 2019 2017 2011 2001 1996 2019 1994 2019 2007
 1994 2007 1997 2006 2013 1994 2008 2008 2019 2019 1999 2007 1993 1995
 2019 2019 2016 2011 2019 2002 2013 2017 2016 2008 2018 2003 2003 2004
 2010 2019 2006 2001 2019 2015 2018 2017 1992 2001 1993 1995 2003 2014
 2008 2013 2019 2017 2019 2019 2006 2015 2007 2005 2017 1998 2019 1999
 2019 2009 2003 1994 2019 1994 2019 2015 1996 1997 1993 2019 1992 1995
 2019 1990 2019 2019 1991 1990 2012 2007 2013 2000 2002 1996 1996 2015
 1993 2013 2013 2009 2019 2019 2002 1997 1998 2004 1996 2015 2016 2005
 1999 1995 1993 2004 2013 1998 2018 2019 2018 2019 1990 2009 1990 2006
 

### Obtendo a quilometragem média por ano

In [11]:
km_medio = km / (2019 - anos)

C:\Users\jeffe\AppData\Local\Temp/ipykernel_14376/433525420.py:1: RuntimeWarning: invalid value encountered in true_divide
  km_medio = km / (2019 - anos)


In [12]:
print(f'{km_medio.dtype}') # Tipo do dado

float64


In [13]:
print(f'{type(km_medio)}\n') # Tipo do objeto ou estrutura do dado

<class 'numpy.ndarray'>



In [14]:
type(km_medio)

numpy.ndarray

In [15]:
km_medio

array([2.77562500e+03, 2.04000000e+02, 1.28010345e+03,            nan,
       1.98130769e+03, 1.53257143e+03,            nan, 7.75990000e+03,
       1.10218889e+04, 4.74725000e+03, 7.56411765e+02, 6.71000000e+02,
       4.98738889e+03,            nan, 4.14570000e+03, 3.85356667e+04,
       6.63557143e+03,            nan, 1.23620000e+04, 7.58650000e+03,
       5.95252941e+03,            nan, 3.92316000e+03, 3.67710714e+03,
                  nan,            nan, 1.93166667e+03,            nan,
       3.46164706e+03, 3.37075000e+03, 1.37104545e+03, 2.22216667e+03,
       1.77200000e+04, 1.20742857e+03, 1.81368000e+04, 1.83229167e+03,
                  nan,            nan, 5.52600000e+02,            nan,
       1.55691667e+04, 2.54762500e+03,            nan, 5.07658824e+03,
                  nan, 5.73823529e+02, 4.66300000e+03, 1.33055556e+02,
                  nan, 5.02181250e+03, 8.55540000e+03, 3.88430769e+03,
       3.56400000e+03, 7.22669231e+03, 3.92722222e+03, 3.24028000e+03,
      

# <font color=green> 2. CARACTERÍSTICAS BÁSICAS DA LINGUAGEM
---

# 2.1 Operações matemáticas

### Operadores aritméticos: $+$, $-$, $*$, $/$, $**$, $\%$, $//$

### Adição ($+$)

In [16]:
2 + 2

4

### Subtração ($-$)

In [17]:
2 - 2

0

### Multiplicação ($*$)

In [18]:
2 * 3 

6

### Divisão ($/$) e ($//$)
A operação divisão sempre retorna um número de ponto flutuante

In [19]:
10 / 3

3.3333333333333335

In [20]:
10 // 3  # Retorno o valor inteiro da divisão.

3

### Exponenciação ($**$)

In [21]:
2 ** 3

8

### Resto da divisão ($\%$)

In [22]:
10 % 3

1

In [23]:
10 % 10

0

### Expressões matemáticas

In [24]:
5 * 2 + 3 * 2

16

In [25]:
(5 * 2) + (3 * 2)

16

In [26]:
5 * (2 + 3) * 2

50

### A variável _

No modo interativo, o último resultado impresso é atribuído à variável _

In [27]:
_

50

In [28]:
5 * 2

10

In [29]:
_ + 3 * 2

16

In [30]:
_ / 2

8.0

# 2.2 Variáveis 

### Nomes de variáveis

- Nomes de variáveis pode começar com letras (a - z, A - Z) ou o caractere *underscore* (_):

    > Altura
    >
    > _peso
    
- O restante do nome pode conter letras, números e o caractere "_":

    > nome_da_variavel
    >
    > _valor
    >
    > dia_28_11_
    

- O nomes são *case sensitive*:

    > Nome_Da_Variável $\ne$ nome_da_variavel $\ne$ NOME_DA_VARIAVEL
    
### <font color=red>Observações:
- Existem algumas palavras reservadas da linguagem que não podem ser utilizadas como nomes de variável:

| |Lista de palavras <br>reservadas em Python| |
|:-------------:|:------------:|:-------------:|
| and           | as           | not           | 
| assert        | finally      | or            | 
| break         | for          | pass          | 
| class         | from         | nonlocal      | 
| continue      | global       | raise         | 
| def           | if           | return        | 
| del           | import       | try           | 
| elif          | in           | while         | 
| else          | is           | with          | 
| except        | lambda       | yield         | 
| False         | True         | None          | 

### Declaração de variáveis

### Operadores de atribuição: $=$, $+=$, $-=$, $*=$, $/=$, $**=$, $\%=$, $//=$

In [31]:
ano_atual= 2019
ano_fabricacao = 2003
km_total = 44410.0

In [32]:
ano_atual

2019

In [33]:
ano_fabricacao

2003

In [34]:
km_total

44410.0

# $$km_{média} = \frac {km_{total}}{(Ano_{atual} - Ano_{fabricação})}$$

### Operações com variáveis

In [35]:
km_media = km_total / (ano_atual - ano_fabricacao)
km_media

2775.625

In [36]:
ano_atual= 2019
ano_fabricacao = 2005
km_total = 44410.0
km_media = km_total / (ano_atual - ano_fabricacao)
km_media

3172.1428571428573

#### Fazendo uma previsão do gasto em 2020 a partir do gasto médio até 2019.

In [37]:
ano_atual= 2019
ano_fabricacao = 2005
km_total = 44410.0
km_media = km_total / (ano_atual - ano_fabricacao)
km_total = km_total + km_media
km_total

47582.142857142855

In [38]:
ano_atual= 2019
ano_fabricacao = 2005
km_total = 44410.0
km_media = km_total / (ano_atual - ano_fabricacao)
km_total += km_media
km_total

47582.142857142855

### Conclusão:
```
"valor = valor + 1" é equivalente a "valor += 1"
```

### Declaração múltipla

In [39]:
ano_atual, ano_fabricacao, km_total = 2019, 2003, 44410.0

In [40]:
ano_atual, ano_fabricacao, km_total

(2019, 2003, 44410.0)

# 2.3 Tipos de dados

Os tipos de dados especificam como números e caracteres serão armazenados e manipulados dentro de um programa. Os tipos de dados básicos do Python são:

1. **Números**
    1. ***int*** - Inteiros
    - ***float*** - Ponto flutuante
- **Booleanos** - Assume os valores True ou False. Essencial quando começarmos a trabalhar com declarações condicionais
- ***Strings*** - Sequência de um ou mais caracteres que pode incluir letras, números e outros tipos de caracteres. Representa um texto.
- **None** - Representa a ausência de valor

### Números

In [41]:
ano_atual = 2019
type(ano_atual)

int

In [42]:
km = 44410.0 
type(km)

float

### Booleanos

In [43]:
zero_km = True

In [44]:
type(zero_km)

bool

In [45]:
zero_km = False

In [46]:
type(zero_km)

bool

### Strings

In [47]:
Nome = 'Jetta Variant'
Nome

'Jetta Variant'

In [48]:
Nome = "Jetta Variant"
Nome

'Jetta Variant'

In [49]:
Nome = "Jetta 'Variant'"
Nome

"Jetta 'Variant'"

In [50]:
Nome = '"Jetta" Variant'
Nome

'"Jetta" Variant'

In [51]:
carro = '''
  Nome
  Idade
  Nota
'''
carro

'\n  Nome\n  Idade\n  Nota\n'

In [52]:
type(carro)

str

### None

In [53]:
quilometragem = None
quilometragem

In [54]:
type(quilometragem)

NoneType

# 2.4 Conversão de tipos

In [55]:
a = 10
b = 20 
c = 'Python é '
d = 'legal'

In [56]:
type(a)

int

In [57]:
type(b)

int

In [58]:
type(c)

str

In [59]:
type(d)

str

In [60]:
a + b

30

In [61]:
c + d

'Python é legal'

In [62]:
#c + a  # Aqui gerará mensagem de erro, pois não podemos concatenar int com string.

### Conversões de tipo

Funções int(), float(), str()

In [63]:
c + str(a)

'Python é 10'

In [64]:
type(str(a))

str

In [65]:
float(a)

10.0

In [66]:
var = 3.1415592
var

3.1415592

In [67]:
int(var)

3

In [68]:
var = 3.99

In [69]:
int(var)

3

# 2.5 Indentação, comentários e formatação de *strings*

### Indentação

Na linguagem Python os programas são estruturados por meio de indentação. Em qualquer linguagem de programação a prática da indentação é bastante útil, facilitando a leitura e também a manutenção do código. Em Python a indentação não é somente uma questão de organização e estilo, mas sim um requisito da linguagem.

In [70]:
ano_atual = 2019
ano_fabricacao = 2019

if (ano_atual == ano_fabricacao):
  print('Verdadeiro')
else:
    print('Falso')

Verdadeiro


### Comentários

Comentários são extremamente importantes em um programa. Consiste em um texto que descreve o que o programa ou uma parte específica do programa está fazendo. Os comentários são ignorados pelo interpretador Python. 

Podemos ter comentários de uma única linha ou de múltiplas linhas.

In [71]:
# Isto é um comentário
ano_atual = 2019
ano_atual

2019

In [72]:
# Isto
# é um 
# comentário
ano_atual = 2019
ano_atual

2019

In [73]:
'''Isto é um
comentário'''
ano_atual = 2019
ano_atual

2019

In [74]:
# Definindo variáveis
ano_atual = 2019
ano_fabricacao = 2019

'''
Estrutura condicional que vamos 
aprender na próxima aula
'''
if (ano_atual == ano_fabricacao):   # Testando se condição é verdadeira
    print('Verdadeiro')
else:                               # Testando se condição é falsa
    print('Falso')

Verdadeiro


### Formatação de *strings*

## *str % valor*
https://docs.python.org/3.6/library/stdtypes.html#old-string-formatting

In [75]:
print('Olá, {}! Este é seu acesso de número {}'.format('Rodrigo', 32))

Olá, Rodrigo! Este é seu acesso de número 32


## *str.format()*

https://docs.python.org/3.6/library/stdtypes.html#str.format

In [76]:
print('Olá, {nome}! Este é seu acesso de número {acessos}'.format(nome = 'Rodrigo',acessos = 32))

Olá, Rodrigo! Este é seu acesso de número 32


## *f-Strings*

https://docs.python.org/3.6/reference/lexical_analysis.html#f-strings

In [77]:
nome = 'Rodrigo'
acessos = 32
print(f'Olá, {nome}! Este é seu acesso de número {acessos}')

Olá, Rodrigo! Este é seu acesso de número 32


# <font color=green> 3. TRABALHANDO COM LISTAS
---

# 3.1 Criando listas

Listas são sequências **mutáveis** que são utilizadas para armazenar coleções de itens, geralmente homogêneos. Podem ser construídas de várias formas:
```
- Utilizando um par de colchetes: [ ], [ 1 ]
- Utilizando um par de colchetes com itens separados por vírgulas: [ 1, 2, 3 ]
```

In [78]:
Acessorios = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [79]:
acessorios2 = np.array(Acessorios)
acessorios2

array(['Rodas de liga', 'Travas elétricas', 'Piloto automático',
       'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento',
       'Sensor crepuscular', 'Sensor de chuva'], dtype='<U24')

In [80]:
type(acessorios2)

numpy.ndarray

In [81]:
type(Acessorios)

list

### Lista com tipos de dados variados

In [82]:
Carro_1 = ['Jetta Variant', 'Motor 4.0 Turbo', 2003, 44410.0, False, ['Rodas de liga', 'Travas elétricas', 'Piloto automático'], 88078.64]
Carro_2 = ['Passat', 'Motor Diesel', 1991, 5712.0, False, ['Central multimídia', 'Teto panorâmico', 'Freios ABS'], 106161.94]

In [83]:
for i in Carro_1:
  print(i)

Jetta Variant
Motor 4.0 Turbo
2003
44410.0
False
['Rodas de liga', 'Travas elétricas', 'Piloto automático']
88078.64


In [84]:
Carro_1

['Jetta Variant',
 'Motor 4.0 Turbo',
 2003,
 44410.0,
 False,
 ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
 88078.64]

In [85]:
Carro_2

['Passat',
 'Motor Diesel',
 1991,
 5712.0,
 False,
 ['Central multimídia', 'Teto panorâmico', 'Freios ABS'],
 106161.94]

In [86]:
Carros = [Carro_1, Carro_2]
Carros

[['Jetta Variant',
  'Motor 4.0 Turbo',
  2003,
  44410.0,
  False,
  ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
  88078.64],
 ['Passat',
  'Motor Diesel',
  1991,
  5712.0,
  False,
  ['Central multimídia', 'Teto panorâmico', 'Freios ABS'],
  106161.94]]

# 3.2 Operações com listas

https://docs.python.org/3.6/library/stdtypes.html#common-sequence-operations

## *x in A*

Retorna **True** se um elemento da lista *A* for igual a *x*.

* Operation x in s
* Result True if an item of s is equal to x, else False
* Notes (1)

In [87]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [88]:
'Rodas de liga' in Acessorios

True

In [89]:
'4 x 4' in Acessorios

False

In [90]:
'Rodas de liga' not in Acessorios

False

In [91]:
'4 x 4' not in Acessorios

True

In [92]:
'Jetta Variant' not in Carro_1

False

In [93]:
Carros = [Carro_1 + Carro_2]
Carros

[['Jetta Variant',
  'Motor 4.0 Turbo',
  2003,
  44410.0,
  False,
  ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
  88078.64,
  'Passat',
  'Motor Diesel',
  1991,
  5712.0,
  False,
  ['Central multimídia', 'Teto panorâmico', 'Freios ABS'],
  106161.94]]

### Aqui é possível percorrer uma string e verificar o valor que está dentro dela.

In [94]:
"gg" in "eggs"

True

## *A + B*

Concatena as listas *A* e *B*.

In [95]:
A = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro']
B = ['Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']

In [96]:
A + B

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

#### Itens extras para testar a documentação do Python:

In [97]:
lists = [[]] * 3
lists

[[], [], []]

In [98]:
lists[0].append(3)

In [99]:
lists

[[3], [3], [3]]

In [100]:
for y in range(1,4):
  lists[0].append(y)
lists

[[3, 1, 2, 3], [3, 1, 2, 3], [3, 1, 2, 3]]

In [101]:
for x in range(0, 3):
    print("We're on time %d" % (x))

We're on time 0
We're on time 1
We're on time 2


In [102]:
lists = [[]] * 3
lists

[[], [], []]

In [103]:
list1 = [[i+1] for i in range(8)]
list1

[[1], [2], [3], [4], [5], [6], [7], [8]]

In [104]:
list1 = [[] for i in range(2)]
list1

[[], []]

In [105]:
list1[0].append("Primeiro item da lista")
list1[1].append("Segundo item da lista")
list1

[['Primeiro item da lista'], ['Segundo item da lista']]

Podemos adicionar itens no final da lista utilizando o função append

In [106]:
list1.append("Terceiro item da lista")

In [107]:
list1

[['Primeiro item da lista'],
 ['Segundo item da lista'],
 'Terceiro item da lista']

In [108]:
len(list1)

3

In [109]:
list1[-1]

'Terceiro item da lista'

In [110]:
list1[len(list1)-1]

'Terceiro item da lista'

In [111]:
lists = [[] for i in range(0,4,2)]
lists

[[], []]

## *len(A)*

Tamanho da lista A.

In [112]:
len(Carro_1)

7

#### Exercicio trabalhando com listas:

In [113]:
carro = [
    'Jetta Variant', 
    'Motor 4.0 Turbo', 
    2003, 
    44410.0, 
    False, 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático'], 
    88078.64
]

In [114]:
'2003' in carro

False

In [115]:
'Rodas de liga' in carro

False

In [116]:
'False' not in carro

True

#### Outros testes

In [117]:
['Rodas de liga'] in carro

False

In [118]:
'Rodas de liga' in carro[5]

True

In [119]:
lists = [[]  for i in range(3)]

In [120]:
for i in range(0,2):
  for j in lists[i]:
    print(j)


In [121]:
print(lists)

[[], [], []]


# 3.3 Seleções em listas

## *A[ i ]*

Retorna o i-ésimo item da lista *A*.

<font color=red>**Observação:**</font> Listas têm indexação com origem no zero.

In [122]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [123]:
Acessorios[0]

'Rodas de liga'

In [124]:
Acessorios[1]

'Travas elétricas'

In [125]:
Acessorios[-1]

'Sensor de chuva'

In [126]:
Carros

[['Jetta Variant',
  'Motor 4.0 Turbo',
  2003,
  44410.0,
  False,
  ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
  88078.64,
  'Passat',
  'Motor Diesel',
  1991,
  5712.0,
  False,
  ['Central multimídia', 'Teto panorâmico', 'Freios ABS'],
  106161.94]]

In [127]:
Carros[0]

['Jetta Variant',
 'Motor 4.0 Turbo',
 2003,
 44410.0,
 False,
 ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
 88078.64,
 'Passat',
 'Motor Diesel',
 1991,
 5712.0,
 False,
 ['Central multimídia', 'Teto panorâmico', 'Freios ABS'],
 106161.94]

In [128]:
Carros[0][0]

'Jetta Variant'

In [129]:
Carros[0][-2][1]

'Teto panorâmico'

## *A[ i : j ]*

Recorta a lista *A* do índice i até o j. Neste fatiamento o elemento com índice i é **incluído** e o elemento com índice j **não é incluído** no resultado.

In [130]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [131]:
Acessorios[2:5] # Eu não incluo indice do último elemento

['Piloto automático', 'Bancos de couro', 'Ar condicionado']

In [132]:
Acessorios[2:]

['Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [133]:
Acessorios[:5]

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado']

#### Exercicios:
Basicamente a ideia é imprimir os valores da lista abaixo com a seleção indicada após a lista:

    letras = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']
   
1) ['A', 'B']

2) ['C', 'D', 'E']

3) ['F', 'G', 'H']

In [134]:
letras = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']
letras

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']

In [135]:
letras[0:2]

['A', 'B']

In [136]:
letras[2:5]

['C', 'D', 'E']

In [137]:
letras[2:-3]

['C', 'D', 'E']

In [138]:
letras[-3:]

['F', 'G', 'H']

#### Exercicio 2:
Considere também os seguintes itens:

1) True

2) 'Teto panorâmico'

3) ['Rodas de liga', 'Travas elétricas', 'Piloto automático']

Assinale a alternativa que mostra o código utilizado para selecionar os itens acima:

In [139]:
carros = [
    [
        'Jetta Variant',
        'Motor 4.0 Turbo',
        2003,
        False,
        ['Rodas de liga', 'Travas elétricas', 'Piloto automático']
    ],
    [
        'Passat',
        'Motor Diesel',
        1991,
        True,
        ['Central multimídia', 'Teto panorâmico', 'Freios ABS']
    ]
]

In [140]:
carros

[['Jetta Variant',
  'Motor 4.0 Turbo',
  2003,
  False,
  ['Rodas de liga', 'Travas elétricas', 'Piloto automático']],
 ['Passat',
  'Motor Diesel',
  1991,
  True,
  ['Central multimídia', 'Teto panorâmico', 'Freios ABS']]]

In [141]:
carros[1][-2]

True

In [142]:
carros[1][-1][1]

'Teto panorâmico'

In [143]:
carros[0][-1]

['Rodas de liga', 'Travas elétricas', 'Piloto automático']

# 3.4 Métodos de listas

https://docs.python.org/3.6/library/stdtypes.html#mutable-sequence-types

## *A.sort()*

Ordena a lista *A*.

In [144]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [145]:
Acessorios.sort()
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

## *A.append(x)*

Adiciona o elemnto *x* no final da lista *A*.

In [146]:
Acessorios.append('4 x 4')
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 '4 x 4']

## *A.pop(i)*

Remove e retorna o elemento de índice i da lista *A*.

<font color=red>**Observação:**</font> Por *default* o método *pop()* remove e retorna o último elemento de uma lista.

In [147]:
Acessorios.pop()

'4 x 4'

In [148]:
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

In [149]:
Acessorios.pop(3)

'Rodas de liga'

In [150]:
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

In [151]:
Acessorios.insert(3,'Rodas de liga')
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

## *A.copy()*

Cria uma cópia da lista *A*.

<font color=red>**Observação:**</font> O mesmo resultado pode ser obtido com o seguinte código: 
```
A[:]
```

In [152]:
Acessorios_2 = Acessorios
Acessorios_2

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

In [153]:
Acessorios_2.append('4 x 4')
Acessorios_2

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 '4 x 4']

#### O Comando Del é utilizado para limpar algum item da memória do Python

In [154]:
# del Acessosrios_2

In [155]:
print(f'{Acessorios} ,\n\n {Acessorios_2}')

['Ar condicionado', 'Bancos de couro', 'Piloto automático', 'Rodas de liga', 'Sensor crepuscular', 'Sensor de chuva', 'Sensor de estacionamento', 'Travas elétricas', '4 x 4'] ,

 ['Ar condicionado', 'Bancos de couro', 'Piloto automático', 'Rodas de liga', 'Sensor crepuscular', 'Sensor de chuva', 'Sensor de estacionamento', 'Travas elétricas', '4 x 4']


In [156]:
## Acessorios.pop()

In [157]:
Acessorios_2 = Acessorios.copy()

In [158]:
Acessorios_2.append('4 x 4')
Acessorios_2

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 '4 x 4',
 '4 x 4']

In [159]:
Acessorios_2

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 '4 x 4',
 '4 x 4']

In [160]:
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 '4 x 4']

In [161]:
Acessorios_3 = Acessorios[:]
Acessorios_3.append('Direção Elétrica')
Acessorios_3

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 '4 x 4',
 'Direção Elétrica']

## Exercicios sobre: Elaborações com listas
Considere a seguinte lista do Python e o resultado obtido após um conjunto de manipulações:

In [1]:

Acessorios = [
    'Rodas de liga', 
    'Travas elétricas', 
    'Piloto automático',
    'Bancos de couro',
    'Ar condicionado'
]
In [2]: Qual código?

Out [2]:

['Airbag',
 'Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Vidros elétricos']
Assinale a alternativa que apresenta o código executado na célula In [2].

Selecione uma alternativa

In [162]:
Acessorios = [
    'Rodas de liga', 
    'Travas elétricas', 
    'Piloto automático',
    'Bancos de couro',
    'Ar condicionado'
]
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado']

#### Opção de solução 1:

In [163]:
Acessorios.pop(1)
Acessorios.append('Airbag')
Acessorios.append('Vidros elétricos')
Acessorios.sort()
Acessorios

['Airbag',
 'Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Vidros elétricos']

#### Opção de solução 2:

In [164]:
Acessorios.append('Airbag')
Acessorios.sort()
Acessorios.pop()
Acessorios.append('Vidros elétricos')
Acessorios

['Airbag',
 'Airbag',
 'Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Vidros elétricos']

# <font color=green> 4. ESTRUTURAS DE REPETIÇÃO E CONDICIONAIS
---

# 4.1 Instrução *for*

#### Formato padrão

```
for <variável> in <coleção>:
    <instruções>
```

### Loops com listas

In [165]:
Acessorios = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [166]:
for item_do_carro in Acessorios:
    print(item_do_carro)

Rodas de liga
Travas elétricas
Piloto automático
Bancos de couro
Ar condicionado
Sensor de estacionamento
Sensor crepuscular
Sensor de chuva


###  List comprehensions

https://docs.python.org/3.6/tutorial/datastructures.html#list-comprehensions

*range()* -> https://docs.python.org/3.6/library/functions.html#func-range

In [167]:
range(10)

range(0, 10)

In [168]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [169]:
for i in range(10):
    print(i**2)

0
1
4
9
16
25
36
49
64
81


In [170]:
print('Segue operação dos quadrados dos valores de 0 a 9:')
for i in range(10):
    print(f'{i}^2 --> {i**2}')

Segue operação dos quadrados dos valores de 0 a 9:
0^2 --> 0
1^2 --> 1
2^2 --> 4
3^2 --> 9
4^2 --> 16
5^2 --> 25
6^2 --> 36
7^2 --> 49
8^2 --> 64
9^2 --> 81


In [171]:
quadrado = []
for i in range(10):
    quadrado.append(i**2)
    
quadrado

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

### Exemplo de List Comprehensions:

In [172]:
[i ** 2 for i in range(10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

# 4.2 Loops aninhados

In [173]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [174]:
for lista in dados:
    print(lista)

['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']
['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento']
['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']


In [175]:
for lista in dados:
    for item in lista:
        print(item)

Rodas de liga
Travas elétricas
Piloto automático
Bancos de couro
Ar condicionado
Sensor de estacionamento
Sensor crepuscular
Sensor de chuva
Central multimídia
Teto panorâmico
Freios ABS
4 X 4
Painel digital
Piloto automático
Bancos de couro
Câmera de estacionamento
Piloto automático
Controle de estabilidade
Sensor crepuscular
Freios ABS
Câmbio automático
Bancos de couro
Central multimídia
Vidros elétricos


In [176]:
Acessorios = []

for lista in dados:
    for item in lista:
        Acessorios.append(item)
        
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Central multimídia',
 'Teto panorâmico',
 'Freios ABS',
 '4 X 4',
 'Painel digital',
 'Piloto automático',
 'Bancos de couro',
 'Câmera de estacionamento',
 'Piloto automático',
 'Controle de estabilidade',
 'Sensor crepuscular',
 'Freios ABS',
 'Câmbio automático',
 'Bancos de couro',
 'Central multimídia',
 'Vidros elétricos']

## *set()*

https://docs.python.org/3.6/library/stdtypes.html#types-set

https://docs.python.org/3.6/library/functions.html#func-set

In [177]:
list(set(Acessorios)) # O set retira os valores duplicados/ O list faz o cast para o tipo de list dos valores que foram trabalhados

['4 X 4',
 'Câmera de estacionamento',
 'Central multimídia',
 'Ar condicionado',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Freios ABS',
 'Câmbio automático',
 'Travas elétricas',
 'Vidros elétricos',
 'Teto panorâmico',
 'Painel digital',
 'Bancos de couro',
 'Rodas de liga',
 'Controle de estabilidade',
 'Sensor de estacionamento']

### List comprehensions

In [178]:
[item for lista in dados for item in lista]

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Central multimídia',
 'Teto panorâmico',
 'Freios ABS',
 '4 X 4',
 'Painel digital',
 'Piloto automático',
 'Bancos de couro',
 'Câmera de estacionamento',
 'Piloto automático',
 'Controle de estabilidade',
 'Sensor crepuscular',
 'Freios ABS',
 'Câmbio automático',
 'Bancos de couro',
 'Central multimídia',
 'Vidros elétricos']

#### # Dica pega o resultado, depois os fors e depois o list e o set para montar o listcomprehension

In [179]:
list(set([item for lista in dados for item in lista]))

['4 X 4',
 'Câmera de estacionamento',
 'Central multimídia',
 'Ar condicionado',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Freios ABS',
 'Câmbio automático',
 'Travas elétricas',
 'Vidros elétricos',
 'Teto panorâmico',
 'Painel digital',
 'Bancos de couro',
 'Rodas de liga',
 'Controle de estabilidade',
 'Sensor de estacionamento']

#### Exercicios:
Considerando a lista dados abaixo:
dados = [ 
    ['A', 'B', 'C'],
    ['D', 'E', 'F'],
    ['G', 'H', 'I']
]COPIAR CÓDIGO
Avalie os itens abaixo:
1) In [1]:
result = []
for lista in dados:
    for item in lista:
        result.append(item)
resultCOPIAR CÓDIGO
Out [1]:
['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I']COPIAR CÓDIGO
2) In [2]:
result_2 = []
for lista in dados:
    result_2 += lista
result_2COPIAR CÓDIGO
Out [2]:
['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I']COPIAR CÓDIGO
3) In [3]:
[item for lista in dados for item in lista]COPIAR CÓDIGO
Out [3]:
['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I']COPIAR CÓDIGO
Quais estão corretos?



Resposta:
Todos os itens estão corretos


Alternativa correta! O item 2 pode parecer uma pegadinha, mas funciona neste caso específico. Lembre-se que o operador de soma (+), quando aplicado em duas listas, retorna a concatenação destas listas.

In [180]:
dados = [ 
    ['A', 'B', 'C'],
    ['D', 'E', 'F'],
    ['G', 'H', 'I']
]
dados

[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']]

In [181]:
result = []
for lista in dados:
    for item in lista:
        result.append(item)
result

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I']

In [182]:
result_2 = []
for lista in dados:
    print(lista)
    print(result_2)
    result_2 = result_2 + lista
    print(result_2)
result_2

['A', 'B', 'C']
[]
['A', 'B', 'C']
['D', 'E', 'F']
['A', 'B', 'C']
['A', 'B', 'C', 'D', 'E', 'F']
['G', 'H', 'I']
['A', 'B', 'C', 'D', 'E', 'F']
['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I']


['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I']

In [183]:
listA = ['A', 'B', 'C']
listB = ['D', 'E', 'F']
listC = []

In [184]:
listC

[]

In [185]:
lista.append('asdfasdf')

In [186]:
print(result_2)

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I']


In [187]:
print(lista)

['G', 'H', 'I', 'asdfasdf']


In [188]:
listC = listB + listB
print(listC,listB,listA)

['D', 'E', 'F', 'D', 'E', 'F'] ['D', 'E', 'F'] ['A', 'B', 'C']


# 4.3 Instrução *if*

#### Formato padrão

```
if <condição>:
     <instruções caso a condição seja verdadeira>
```

### Operadores de comparação: $==$, $!=$, $>$, $<$, $>=$, $<=$
### e
### Operadores lógicos: $and$, $or$, $not$

In [189]:
# 1º item da lista - Nome do veículo
# 2º item da lista - Ano de fabricação
# 3º item da lista - Veículo é zero km?

dados = [
    ['Jetta Variant', 2003, False],
    ['Passat', 1991, False],
    ['Crossfox', 1990, False],
    ['DS5', 2019, True],
    ['Aston Martin DB4', 2006, False],
    ['Palio Weekend', 2012, False],
    ['A5', 2019, True],
    ['Série 3 Cabrio', 2009, False],
    ['Dodge Jorney', 2019, False],
    ['Carens', 2011, False]
]
dados

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['DS5', 2019, True],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [190]:
for lista in dados:
    print(lista)

['Jetta Variant', 2003, False]
['Passat', 1991, False]
['Crossfox', 1990, False]
['DS5', 2019, True]
['Aston Martin DB4', 2006, False]
['Palio Weekend', 2012, False]
['A5', 2019, True]
['Série 3 Cabrio', 2009, False]
['Dodge Jorney', 2019, False]
['Carens', 2011, False]


In [191]:
for lista in dados:
    print(lista[2])

False
False
False
True
False
False
True
False
False
False


In [192]:
for lista in dados:
    if (lista[2] == True):
        print(lista)

['DS5', 2019, True]
['A5', 2019, True]


In [193]:
for lista in dados:
    if (lista[2]):
        print(lista)
        

['DS5', 2019, True]
['A5', 2019, True]


In [194]:
zero_km_S = []
for lista in dados:
    if (lista[2]):
        zero_km_S.append(lista)

zero_km_S

[['DS5', 2019, True], ['A5', 2019, True]]

In [195]:
zero_km_S = []
zero_km_N = []

for lista in dados:
    if (lista[2]):
        zero_km_S.append(lista)
    else:
        zero_km_N.append(lista)
        
print(f'Lista de carros 0 km: \n {zero_km_S}')
print(f'Lista de carros usados: \n {zero_km_N}')

Lista de carros 0 km: 
 [['DS5', 2019, True], ['A5', 2019, True]]
Lista de carros usados: 
 [['Jetta Variant', 2003, False], ['Passat', 1991, False], ['Crossfox', 1990, False], ['Aston Martin DB4', 2006, False], ['Palio Weekend', 2012, False], ['Série 3 Cabrio', 2009, False], ['Dodge Jorney', 2019, False], ['Carens', 2011, False]]


### List comprehensions

In [196]:
[lista for lista in dados if lista[2] ==True]

[['DS5', 2019, True], ['A5', 2019, True]]

In [197]:
[lista for lista in dados if lista[2] == False]

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

# 4.4 Instruções *if-else* e *if-elif-else*

#### Formato padrão

```
if <condição>:
    <instruções caso a condição seja verdadeira>
else:
    <instruções caso a condição não seja verdadeira>
```

In [198]:
zero_km_S, zero_km_N  = [], []

for lista in dados:
    if (lista[2] == True):
        zero_km_S.append(lista)
    else:
        zero_km_N.append(lista)

In [199]:
zero_km_S

[['DS5', 2019, True], ['A5', 2019, True]]

In [200]:
zero_km_N

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

#### Formato padrão

```
if <condição 1>:
    <instruções caso a condição 1 seja verdadeira>
elif <condição 2>:
    <instruções caso a condição 2 seja verdadeira>
elif <condição 3>:
    <instruções caso a condição 3 seja verdadeira>
                        .
                        .
                        .
else:
    <instruções caso as condições anteriores não sejam verdadeiras>
```

In [201]:
dados

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['DS5', 2019, True],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [202]:
print('AND')
print(f'(True and True) o resultado é: {True and True}')
print(f'(True and False) o resultado é: {True and False}')
print(f'(False and True) o resultado é: {False and True}')
print(f'(False and False) o resultado é: {False and False}')

AND
(True and True) o resultado é: True
(True and False) o resultado é: False
(False and True) o resultado é: False
(False and False) o resultado é: False


In [203]:
print('OR')
print(f'(True or True) o resultado é: {True or True}')
print(f'(True or False) o resultado é: {True or False}')
print(f'(False or True) o resultado é: {False or True}')
print(f'(False or False) o resultado é: {False or False}')

OR
(True or True) o resultado é: True
(True or False) o resultado é: True
(False or True) o resultado é: True
(False or False) o resultado é: False


In [204]:
A, B, C = [], [], []

for lista in dados:
    if(lista[1] <= 2000):
        A.append(lista)
    elif(lista[1] > 2000 and lista[1] <= 2010):
        B.append(lista)
    else:
        C.append(lista)        

In [205]:
A

[['Passat', 1991, False], ['Crossfox', 1990, False]]

In [206]:
B

[['Jetta Variant', 2003, False],
 ['Aston Martin DB4', 2006, False],
 ['Série 3 Cabrio', 2009, False]]

In [207]:
C

[['DS5', 2019, True],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [208]:
A, B, C = [], [], []

for lista in dados:
    if(lista[1] <= 2000):
        A.append(lista)
    elif(2000 < lista[1] <= 2010): # O Python também aceita colocarmos intervalos, porém outras linguagens não.
        B.append(lista)
    else:
        C.append(lista)        

# <font color=green> 5. NUMPY BÁSICO
---

Numpy é a abreviação de Numerical Python e é um dos pacotes mais importantes para processamento numérico em Python. Numpy oferece a base para a maioria dos pacotes de aplicações científicas que utilizem dados numéricos em Python (estruturas de dados e algoritmos). Pode-se destacar os seguintes recursos que o pacote Numpy contém:

- Um poderoso objeto array multidimensional;
- Funções matemáticas sofisticadas para operações com arrays sem a necessidade de utilização de laços *for*;
- Recursos de algebra linear e geração de números aleatórios

Além de seus óbvios usos científicos, o pacote NumPy também é muito utilizado em análise de dados como um eficiente contêiner multidimensional de dados genéricos para transporte entre diversos algoritmos e bibliotecas em Python.

**Versão:** 1.16.5

**Instalação:** https://scipy.org/install.html

**Documentação:** https://numpy.org/doc/1.16/

### Pacotes

Existem diversos pacotes Python disponíveis para download na internet. Cada pacote tem como objetivo a solução de determinado tipo de problema e para isso são desenvolvidos novos tipos, funções e métodos.

Alguns pacotes são bastante utilizados em um contexto de ciência de dados como por exemplo:

- Numpy
- Pandas
- Scikit-learn
- Matplotlib

Alguns pacotes não são distribuídos com a instalação default do Python. Neste caso devemos instalar os pacotes que necessitamos em nosso sistema para podermos utilizar suas funcionalidades.

### Importando todo o pacote

In [209]:
!pip3 install numpy

In [210]:
import numpy

https://numpy.org/doc/1.16/reference/generated/numpy.arange.html

In [211]:
numpy.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Importando todo o pacote e atribuindo um novo nome 

In [212]:
import numpy as np

In [213]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Importando parte do pacote

In [214]:
from numpy import arange # Da biblioteca numpy eu quero que seja importado somente a função arange.

In [215]:
arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 5.1 Criando arrays Numpy

In [216]:
import numpy as np

### A partir de listas

https://numpy.org/doc/1.16/user/basics.creation.html

In [217]:
km = np.array([1000,2300,4987,1500])

In [218]:
km

array([1000, 2300, 4987, 1500])

In [219]:
type(km)

numpy.ndarray

https://numpy.org/doc/1.16/user/basics.types.html

In [220]:
km.dtype

dtype('int32')

### A partir de dados externos

https://numpy.org/doc/1.16/reference/generated/numpy.loadtxt.html

In [221]:
km = np.loadtxt(fname = 'data/carros-km.txt', dtype=int)

In [222]:
km

array([ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
        99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
        46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
            0,      0,   5795,      0,  58848,  94381,  30163,  53332,
        17720,  33808,  90684,  43975,      0,      0,   5526,      0,
        93415,  40762,      0,  86302,      0,   9755,  69945,   2395,
            0,  80349,  85554,  50496,  67716,  93947,  35345,  81007,
       119513,      0,      0,      0,      0,      0, 118895,  48509,
       100912,  95649,      0,  90495,      0,  29132,  23802,  84992,
        54395,  26731,  44329, 118236, 113808,    610,      0,      0,
        12887,  79607,  90924,  42733,      0,      0, 117714, 113885,
            0,  30511,  74867, 119760,   8356,  64247,  88661,   4539,
       110116,  33215,  92001,      0,  81708,  70641,      0,  91277,
        26544,  52596,  47503,  89056,  28834, 110564,  56638,  17357,
      

In [223]:
km.dtype

dtype('int32')

### Arrays com duas dimensões

In [224]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [225]:
Acessorios = np.array(dados)
Acessorios

array([['Rodas de liga', 'Travas elétricas', 'Piloto automático',
        'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento',
        'Sensor crepuscular', 'Sensor de chuva'],
       ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4',
        'Painel digital', 'Piloto automático', 'Bancos de couro',
        'Câmera de estacionamento'],
       ['Piloto automático', 'Controle de estabilidade',
        'Sensor crepuscular', 'Freios ABS', 'Câmbio automático',
        'Bancos de couro', 'Central multimídia', 'Vidros elétricos']],
      dtype='<U24')

In [226]:
km.shape # shape é um attribute de array, mas não é um atributo de lista.

(258,)

In [227]:
Acessorios.shape

(3, 8)

### Comparando desempenho com listas

In [228]:
np_array = np.arange(1000000)

In [229]:
py_list = list(range(1000000))

In [230]:
%time for _ in range(100):np_array *= 2

Wall time: 107 ms


In [231]:
%time for _ in range(100):py_list = [x * 2 for x in py_list ]

Wall time: 20.7 s


# 5.2 Operações aritméticas com arrays Numpy

### Operações entre arrays e constantes

In [232]:
km = [44410., 5712., 37123., 0., 25757.]
anos = [2003, 1991, 1990, 2019, 2006]

#### O erro que tive no início do projeto se explica pelo fato que não é possível realizar operações matemáticas entre listas e inteiro, porém podemos utilizar array numpy e inteiro para essa tarefa.

In [233]:
idade = 2019 - anos

TypeError: unsupported operand type(s) for -: 'int' and 'list'

In [ ]:
km = np.array([44410., 5712., 37123., 0., 25757.])
anos = np.array([2003, 1991, 1990, 2019, 2006])

In [ ]:
# idade = 2019 - anos

In [ ]:
idade

### Operações entre arrays

In [ ]:
km_media = km / idade

In [ ]:
km_media

In [ ]:
44410 / (2019 - 2003)

In [ ]:
5712 / (2019 - 1991)

### Operações com arrays de duas dimensões

In [234]:
dados = np.array([km, anos])
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [ ]:
dados.shape

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [ ]:
dados[0]

In [ ]:
dados[1]

In [ ]:
km_media = dados[0] / (2019 - dados[1])

In [ ]:
km_media

# 5.3 Seleções com arrays Numpy

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [ ]:
dados

![1410-img02.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img02.png)

### Indexação 

<font color=red>**Observação:**</font> A indexação tem origem no zero.

In [ ]:
contador = np.arange(10)
contador

In [ ]:
contador[0]

In [ ]:
item = 6
index = item - 1
contador[index]

In [ ]:
contador[-1]

In [ ]:
dados[0]

In [ ]:
dados[1]

## <font color=green>**Dica:**</font>
### *ndarray[ linha ][ coluna ]* ou *ndarray[ linha, coluna ]*

In [ ]:
dados[1][2]

In [ ]:
dados[1,2]

 ### Fatiamentos
 
A sintaxe para realizar fatiamento em um array Numpy é $i : j : k$ onde $i$ é o índice inicial, $j$ é o índice de parada, e $k$ é o indicador de passo ($k\neq0$)
 
<font color=red>**Observação:**</font> Nos fatiamentos (*slices*) o item com índice i é **incluído** e o item com índice j **não é incluído** no resultado.

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [ ]:
contador = np.arange(10)
contador

In [ ]:
contador[1:4:1]

In [ ]:
contador[1:8:2]

In [ ]:
contador[::2]

In [ ]:
contador[1::2]

In [ ]:
dados

In [ ]:
dados[:][1:4] # Erroado

In [ ]:
dados[:,1:3]

In [ ]:
dados[:,1:3][0] / (2019 - dados[:,1:3][1])

In [ ]:
dados[0] / (2019 - dados[1])

### Indexação com array booleano

<font color=red>**Observação:**</font> Seleciona um grupo de linhas e colunas segundo os rótulos ou um array booleano.

In [ ]:
contador = np.arange(10)
contador

In [ ]:
contador > 5

In [ ]:
contador[contador > 5]

In [ ]:
contador[[False, False, False, False, False, False,  True,  True,  True,
        True]]

In [ ]:
dados

In [ ]:
dados[1] >2000

In [ ]:
dados[:,dados[1] > 2000]

In [ ]:
dados[:,dados[1] > 2000][0] / (2019 - dados[:,dados[1] > 2000][1])

In [ ]:
filtro = dados[:,dados[1] > 2003]
filtro

In [ ]:
filtro[0] / (2019 - filtro[1])

In [ ]:
#Exercicio:

dados_exercicio = np.array(
    [
        ['Roberto', 'casado', 'masculino'],
        ['Sheila', 'solteiro', 'feminino'],
        ['Bruno', 'solteiro', 'masculino'],
        ['Rita', 'casado', 'feminino']
    ]
)
dados_exercicio

In [ ]:
dados_exercicio[0::2,:2]

In [ ]:
dados_exercicio[:2,0::2]

# 5.4 Atributos e métodos de arrays Numpy

### Atributos

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#array-attributes

In [235]:
dados = np.array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

## *ndarray.shape*

Retorna uma tupla com as dimensões do array.

In [237]:
dados.shape # possui na primeira linha a quantidade de linhas e na segunda a quantidade de colunas

(2, 5)

## *ndarray.ndim*

Retorna o número de dimensões do array.

In [238]:
dados.ndim

2

## *ndarray.size*

Retorna o número de elementos do array.

In [239]:
dados.size

10

## *ndarray.dtype*

Retorna o tipo de dados dos elementos do array.

In [240]:
dados.dtype

dtype('float64')

## *ndarray.T*

Retorna o array transposto, isto é, converte linhas em colunas e vice versa.

In [241]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [242]:
dados.T

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

In [243]:
dados.transpose() # equivalente de fazer dados.T --> Ambos fazer a transporta

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

### Métodos

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#array-methods

## *ndarray.tolist()*

Retorna o array como uma lista Python.

In [244]:
dados.tolist()

[[44410.0, 5712.0, 37123.0, 0.0, 25757.0],
 [2003.0, 1991.0, 1990.0, 2019.0, 2006.0]]

## *ndarray.reshape(shape[, order])*

Retorna um array que contém os mesmos dados com uma nova forma.

In [247]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [248]:
contador.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [249]:
contador.reshape((5,2), order='C') # O Comando acima por padrão traz o formato de ordenação do C
                                   # , mas podemos utilizar o padrão do Fortran como pode ser visto a abaixo.

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [250]:
contador.reshape((5,2), order='F')

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [259]:
km = [44410, 5712, 37123, 0, 25757]
anos = [2003, 1991, 1990, 2019, 2006]

In [260]:
info_carros = km + anos
info_carros

[44410, 5712, 37123, 0, 25757, 2003, 1991, 1990, 2019, 2006]

In [262]:
np.array(info_carros).reshape(2,5)

array([[44410,  5712, 37123,     0, 25757],
       [ 2003,  1991,  1990,  2019,  2006]])

In [265]:
np.array(info_carros).reshape((5,2), order='F')

array([[44410,  2003],
       [ 5712,  1991],
       [37123,  1990],
       [    0,  2019],
       [25757,  2006]])

## *ndarray.resize(new_shape[, refcheck])*

Altera a forma e o tamanho do array.

In [266]:
dados_new = dados.copy()
dados_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [267]:
dados_new.resize(3,5) # Gera erro, pois tem que pedir para não checar a referência para gera um array sem verificar 

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [268]:
dados_new.resize((3,5), refcheck=False)

In [269]:
dados_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.],
       [    0.,     0.,     0.,     0.,     0.]])

In [270]:
dados_new[2] = dados_new[0] / (2019 - dados_new[1]) # Adicionando o resultado km / ano na terceira linha do array numpy

C:\Users\jeffe\AppData\Local\Temp/ipykernel_14376/4186527466.py:1: RuntimeWarning: invalid value encountered in true_divide
  dados_new[2] = dados_new[0] / (2019 - dados_new[1])


In [271]:
dados_new

array([[44410.        ,  5712.        , 37123.        ,     0.        ,
        25757.        ],
       [ 2003.        ,  1991.        ,  1990.        ,  2019.        ,
         2006.        ],
       [ 2775.625     ,   204.        ,  1280.10344828,            nan,
         1981.30769231]])

# 5.5 Estatísticas com arrays Numpy

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#calculation

e

https://numpy.org/doc/1.16/reference/routines.statistics.html

e

https://numpy.org/doc/1.16/reference/routines.math.html

In [273]:
anos = np.loadtxt(fname = "data/carros-anos.txt", dtype = int)
km = np.loadtxt(fname = "data/carros-km.txt")
valor = np.loadtxt(fname = "data/carros-valor.txt")

In [275]:
anos.shape

(258,)

https://numpy.org/doc/1.16/reference/generated/numpy.column_stack.html

In [276]:
dataset = np.column_stack((anos, km, valor))
dataset

array([[2.0030000e+03, 4.4410000e+04, 8.8078640e+04],
       [1.9910000e+03, 5.7120000e+03, 1.0616194e+05],
       [1.9900000e+03, 3.7123000e+04, 7.2832160e+04],
       [2.0190000e+03, 0.0000000e+00, 1.2454907e+05],
       [2.0060000e+03, 2.5757000e+04, 9.2612100e+04],
       [2.0120000e+03, 1.0728000e+04, 9.7497730e+04],
       [2.0190000e+03, 0.0000000e+00, 5.6445200e+04],
       [2.0090000e+03, 7.7599000e+04, 1.1231044e+05],
       [2.0100000e+03, 9.9197000e+04, 1.2071627e+05],
       [2.0110000e+03, 3.7978000e+04, 7.6566490e+04],
       [2.0020000e+03, 1.2859000e+04, 7.1647590e+04],
       [2.0070000e+03, 8.0520000e+03, 7.3919530e+04],
       [2.0010000e+03, 8.9773000e+04, 1.1273299e+05],
       [2.0190000e+03, 0.0000000e+00, 5.3183380e+04],
       [2.0090000e+03, 4.1457000e+04, 1.2748842e+05],
       [2.0160000e+03, 1.1560700e+05, 5.9910400e+04],
       [2.0120000e+03, 4.6449000e+04, 6.1118590e+04],
       [2.0190000e+03, 0.0000000e+00, 8.8552390e+04],
       [2.0160000e+03, 3.708

In [277]:
dataset.shape

(258, 3)

## *np.mean()*

Retorna a média dos elementos do array ao longo do eixo especificado.

In [279]:
np.mean(dataset, axis = 0 ) # Quando utilizamos "axis=0" informamos que queria fazer a média de cada uma das colunas
# Se não utilizamos essa parâmetro, o numpy fazer a média de todos os valores do dataset

array([ 2007.51162791, 44499.41472868, 98960.51310078])

In [ ]:
np.mean(dataset, axis = 1 ) # faria pela linha

In [283]:
np.mean(dataset[:,1]) # A primeira parte está ":" porque eu quero todas as linhas e
                    # a segunda parte está com o 1 porque eu só quero a segunda linha

44499.41472868217

In [284]:
np.mean(dataset[:,2])

98960.51310077519

## *np.std()*

Retorna o desvio padrão dos elementos do array ao longo do eixo especificado.

In [285]:
np.std(dataset[:,2])

29754.101150388564

## *ndarray.sum()*

Retorna a soma dos elementos do array ao longo do eixo especificado.

In [286]:
dataset.sum(axis = 0)

array([  517938.        , 11480849.        , 25531812.37999999])

In [287]:
dataset[:,1].sum(axis = 0)

11480849.0

## *np.sum()*

Retorna a soma dos elementos do array ao longo do eixo especificado.

In [288]:
np.sum(dataset, axis = 0)

array([  517938.        , 11480849.        , 25531812.37999999])

In [289]:
np.sum(dataset[:,2])

25531812.38